//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Karaokay.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail
    {
        public string BillID { get; set; }
        public string OrderID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> TotalPrice { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual Items Items { get; set; }
    }
}
