//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Karaokay.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KaraOkayEntities : DbContext
    {
        public KaraOkayEntities()
            : base("name=KaraOkayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<bill> bill { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<reports> reports { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<BillDetail> BillDetail { get; set; }
    }
}
